.TH lso 1 "" lso\-VERSION

.SH NAME
lso \- list X outputs

.SH SYNOPSIS
.B lso
.RB [\- acdpsuhv ]

.SH DESCRIPTION
.B lso
is a simple tool to list available X outputs.

.RB "Each output has exactly one state of the group " "connection " "and " "rank " set.

.RS
.BR connections " := connected | disconnected | unknown connection"
.br
.BR ranks "       := primary | secondary"
.RE

.SH OPTIONS

.TP
.B \-a
Outputs have to match the \fBconnection\fR \fIa\fRnd \fBrank\fR state.

.TP
.B \-c
.RB "List " "connected " outputs.

.TP
.B \-d
.RB "List " "disconnected " outputs.

.TP
.B \-p
.RB "List " "primary " "outputs. Will always be printed at last."

.TP
.B \-s
.RB "List " "secondary " "(not as primary marked) outputs."

.TP
.B \-u
.RB "List outputs with " "unknown connection " status.

.TP
.B \-h
Prints a short help to stderr, then exits successfully.

.TP
.B \-v
Prints version information to stderr, then exits successfully.


.SH ENVIRONMENT VARIABLES
.IP DISPLAY
Specifies the hardware display name, which determines the display and communications domain to be used.


.SH EXAMPLES
.EX
.RB "$ " "lso         " " #=> List all available outputs"
.RB "$ " "lso -pc     " " #=> List primary and connected outputs"
.RB "$ " "lso -pac    " " #=> List primary outputs that are also connected"
.RB "$ " "lso -sacd   " " #=> List secondary outputs that are also either connected or disconnected"

.BR "  lso -c " == " lso -caps " != " lso -cps"
.EE

.SH LICENSE
See the LICENSE file for the terms of redistribution.

.SH SEE ALSO
.BR xrandr (1)
